backend:
  name: github
  repo: AD-Gomez/CayadServices
  branch: main
  base_url: https://auth.cayadservices.com
  auth_endpoint: auth
  site_domain: cayadservices.com # Agrega esto expl√≠citamente

display_url: https://cayadservices.com
media_folder: "public/img"
public_folder: "/img"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    extension: "md" # Fuerza a leer solo archivos .md
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }