backend:
  name: github
  repo: AD-Gomez/CayadServices
  branch: main
  base_url: https://auth.cayadservices.com
  auth_endpoint: auth
  site_domain: cayadservices.com # Agrega esto explícitamente

display_url: https://cayadservices.com
media_folder: "public/img"
public_folder: "/img"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Estado (Mapa)", name: "state", widget: "string", default: "published" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Descripción", name: "description", widget: "string" }
      - { label: "Imagen", name: "image", widget: "image", required: false }
      - { label: "Cuerpo", name: "body", widget: "markdown" }